---
title: "Final Project"
author: "Charlie Booker"
date: "November 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plyr)
library(knitr)
library(fs)
library(graphics)
#this library needed to read in excel
library(readxl)
#these libraries will be needed to plot map
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(janitor)
library(kableExtra)
library(dplyr)
```

```{r, echo = FALSE, message = FALSE}
#loading in data
construction <- read_excel("construction.xlsx", skip = 1)
```

```{r, echo = FALSE, message = FALSE}
#This theme will get rid of the gridlines but keep the legend
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )



#chosing the state data map
states <- map_data("state")
#selecting texas as the state to use
texas <- states %>%
  subset(region == "texas")

#Putting in county lines. First I need all county lines and then I will subset for Texas to get Texas county lines
counties <- map_data("county")
tx_county <- counties %>%
  subset(region == "texas") %>%
  #going to filter for the Houston counties
  subset(subregion %in% c("harris", "galveston", "brazoria", "fort bend", "waller", "montgomery", "chambers"))

#looking at texas map
tx_base <- texas %>%
  ggplot(mapping = aes(x = long, y = lat, group = group)) + coord_fixed(1.3) + geom_polygon(color = "black", fill = "gray")

#This was before, I used gg2 as my Houston map, so I'm commenting this out

#gg1 <- tx_base + theme_nothing() +
  #putting in county lines
  #geom_polygon(data = tx_county, fill = NA, color = "white") + 
  #geom_polygon(color = "black", fill = NA)
#this puts the state border on top


#plotting the points of new construction on the whole state map
#gg1 + geom_point(data = construction, aes(x = Longitude, y = Latitude, group = NA), color = "yellow", size = 1)

#trying to get Houston plot
hou_base <- tx_county %>%
  ggplot(mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + geom_polygon(color = "black", fill = "gray")

#repeating steps from earlier but Houston counties instead of whole state of Texas. Trying to get Houston plot continued
gg2 <- hou_base + #ditch_the_axes + 
  geom_polygon(data = tx_county, fill = NA, color = "white") + geom_polygon(color = "black", fill = NA)

gg2 + geom_point(data = construction, aes(x = Longitude, y = Latitude, group = NA), color = "black", size = 1, alpha = .5) +
   geom_point(data = construction, aes(x = Longitude, y = Latitude, 
    color = Category, group = NA), size = .8, alpha = .5) + scale_color_manual(values = c("red", "blue", "yellow")) + 
  theme(legend.text = element_text(size = 12)) + theme(legend.title = element_text(size = 15, face = "bold"))





```

```{r}
class_df <- read_excel("Market Summary by Class - Houston 201811.xlsx", skip = 1) %>%
  clean_names()

class1_df <- class_df %>% 
  select(submarket, class, rental_rate_sf_mo) %>%
  filter(class %in% c("Class A", "Class B", "Class C", "Class D")) %>%
  spread(class, rental_rate_sf_mo)

class1_df <- rename(class1_df, c("submarket" = "Submarket"))

kable(class1_df, caption = "Square Foot Monthly Rental Rate by Class") %>% kable_styling(full_width = F) %>%
  row_spec(2, bold = T)
```


```{r}
#getting ready to perfect the class table
construction_merge <- construction %>%
  select(Submarket, Section)

class_complete <- left_join(class1_df, construction_merge, by = "Submarket")

#putting in sections for those with NA
working_class <- class_complete %>%
  filter(!Section %in% c("Northwest Houston", "Northeast Houston", "Southwest Houston", "Southeast Houston", "Central Houston"))

class1_df <- class1_df %>%
  mutate(Section = case_when(Submarket %in% c("Sharpstown/ Westwood", "Woodlake/ Westheimer", "Westpark/ Bissonnet", "Westchase", "Braeswood/ Fondren SW", "Almeda/ South Main", "Galleria/ Uptown", "Energy Corridor/ CityCentre/ Briar Forest", "Alief", "Sugar Land/ Stafford/ Sienna", "Richmond/ Rosenberg" ) ~
                               "Southwest Houston",
                             
                             Submarket %in% c("Alvin/ Angleton/ Lake Jackson", "Hwy 288 South/ Pearland West", "U of H/ I-45 South", "Beltway 8 / I-45 South", "Pasadena/ Deer Park/ La Porte", "Friendswood/ Pearland East", "Clear Lake/ Webster/ League City", "Baytown", "Dickinson/ Galveston") ~
                               "Southeast Houston",
                             
                             Submarket %in% c("Montrose/ Museum/ Midtown", "Highland Village/ Upper Kirby/ West U", "Med Center/ Braes Bayou", "Heights/ Washington Ave", "Downtown") ~ "Central Houston",
                     
                             Submarket %in% c("Inwood/ Hwy 249", "Brookhollow/ Northwest Crossing", "Memorial/ Spring Branch", "Willowbrook/ Champions/ Ella", "Jersey Village/ Cypress", "Bear Creek/ Copperfield/ Fairfield", "Katy/ Cinco Ranch/ Waterside", "Tomball/ Spring", "Woodlands/ Conroe South", "Conroe North/ Montgomery") ~ 
                               "Northwest Houston",
                             
                             Submarket %in% c("Northeast Houston/ Crosby", "Greenspoint/ Northborough/ Aldine", "FM 1960 East/ IAH Airport", "I-10 East/ Woodforest/ Channelview", "I-69 North", "Northline", "Lake Houston/ Kingwood") ~ 
                               "Northeast Houston",
                             TRUE ~ "NA"))

class1_df[is.na(class1_df)] <- 0
```


```{r}
averaging_number <- class1_df %>%
  group_by(Section) %>%
  tally()

detach(package:plyr)

averaging <- class1_df %>%
  select(`Class A`, `Class B`, `Class C`, `Class D`, Section, Submarket) %>%
  group_by(Section) %>%
  arrange(Section) %>%
  group_by(Section) %>%
  summarise("Class A" = mean(`Class A`),
            "Class B" = mean(`Class B`),
            "Class C" = mean(`Class C`),
            "Class D" = mean(`Class D`)) %>%
  filter(!Section %in% "NA") 
 
library(plyr)
averaging <- rename(averaging, c("Section" = "Submarket"))
detach(package:plyr)

#preparing Northwest Houston
nw_averaging <- averaging %>%
  filter(Submarket == "Northwest Houston")
nw_class <- class1_df %>%
  filter(Section == "Northwest Houston") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)
#binding northwest
nw <- rbind(nw_averaging, nw_class)

#preparing Northeast Houston
ne_averaging <- averaging %>%
  filter(Submarket == "Northeast Houston")
ne_class <- class1_df %>%
  filter(Section == "Northeast Houston") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)
#binding northeast
ne <- rbind(ne_averaging, ne_class)

#preparing Southwest Houston
sw_averaging <- averaging %>%
  filter(Submarket == "Southwest Houston")
sw_class <- class1_df %>%
  filter(Section == "Southwest Houston") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)
#binding southwest
sw <- rbind(sw_averaging, sw_class)

#preparing Southeast Houston
se_averaging <- averaging %>%
  filter(Submarket == "Southeast Houston")
se_class <- class1_df %>%
  filter(Section == "Southeast Houston") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)
#binding northwest
se <- rbind(se_averaging, se_class)

#preparing Central Houston
ce_averaging <- averaging %>%
  filter(Submarket == "Central Houston")
ce_class <- class1_df %>%
  filter(Section == "Central Houston") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)
#binding northwest
ce <- rbind(ce_averaging, ce_class)

#preparing all markets
all <- class1_df %>%
  filter(Submarket == "All") %>%
  select(Submarket, `Class A`, `Class B`, `Class C`, `Class D`)

#making full table for kable
full_table <- rbind(all, sw, nw, ce, ne, se)
#setting 0 equal to NA
full_table[full_table == 0] <- NA
```



